print('a', 'b', 'c', end=' ')
print('a', 'b', 'c', end=' ')
print('a', 'b', 'c', end=' ')
print('a', 'b', 'c', end=' ')
print()
print('a', 'b', 'c', end=' ')
print('a', 'b', 'c', end=' ')
print('a', 'b', 'c', end=' ')
print('a', 'b', 'c', end=' ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')
# print('d','h','t', sep=' ***** ')